
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "21e890b4117fc810afb6fb058e8055d564f03382",
 "version": "1.7.0+264.g21e890b"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
